language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3 CELERY=2.5.5
  - DJANGO=1.3 CELERY=3.0.0
  - DJANGO=1.4 CELERY=2.5.5
  - DJANGO=1.4 CELERY=3.0.0
install:
  - pip install django==$DJANGO --use-mirrors
  - pip install celery==$CELERY django-celery==$CELERY --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python test_project/manage.py test useful -v2
  - pep8 --exclude=*urls.py useful -v
