language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3
  - DJANGO=1.4
install:
  - pip install django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python test_project/manage.py test -v2
